---
services:
  -
    class: org.jlab.clara.examples.engines.E1
    name: E1
  -
    class: org.jlab.clara.examples.engines.E2
    name: E2
  -
    class: org.jlab.clara.examples.engines.E5
    name: E5
